const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#333' },
  pokedexFrame: {
    flex: 1,
    backgroundColor: '#DC0A2D', // Classic Pokedex Red
    margin: 10,
    borderRadius: 20,
    borderWidth: 5,
    borderColor: '#8B0000',
    padding: 20,
  },
  topBar: { flexDirection: 'row', marginBottom: 20 },
  blueLight: { width: 40, height: 40, borderRadius: 20, backgroundColor: '#00D1FF', borderWidth: 3, borderColor: 'white', marginRight: 10 },
  redLight: { width: 15, height: 15, borderRadius: 10, backgroundColor: '#FF0000', marginRight: 5 },
  yellowLight: { width: 15, height: 15, borderRadius: 10, backgroundColor: '#FFCC00' },
  scannerScreen: {
    flex: 1,
    backgroundColor: '#000',
    borderRadius: 10,
    padding: 20,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 4,
    borderColor: '#555',
  },
  imagePlaceholder: { width: 180, height: 180, backgroundColor: '#222', justifyContent: 'center', alignItems: 'center', marginBottom: 20, borderStyle: 'dashed', borderWidth: 2, borderColor: '#444' },
  retroText: { color: '#00FF00', fontFamily: 'monospace', fontWeight: 'bold', marginBottom: 10 },
  pixelText: { color: 'white', fontFamily: 'monospace' },
  scanBtn: { backgroundColor: '#FFCC00', padding: 15, borderRadius: 5, width: '100%' },
  scanBtnText: { textAlign: 'center', fontWeight: 'bold', fontSize: 18, color: '#333' },
  entryScreen: { flex: 1, backgroundColor: '#E0E0E0', borderRadius: 10, padding: 15 },
  entryTitle: { fontSize: 24, fontWeight: 'bold', color: '#333', textAlign: 'center', marginBottom: 10 },
  spriteContainer: { backgroundColor: 'white', padding: 10, borderRadius: 10, alignItems: 'center', marginBottom: 15, borderWidth: 2, borderColor: '#999' },
  sprite: { width: 150, height: 150 },
  statsCard: { backgroundColor: '#333', padding: 10, borderRadius: 5 },
  statLine: { color: '#00FF00', fontFamily: 'monospace', fontSize: 14 },
  hpBarContainer: { flexDirection: 'row', alignItems: 'center', marginTop: 5 },
  hpBar: { flex: 1, height: 8, backgroundColor: '#FF0000', borderRadius: 4 },
  description: { marginTop: 15, color: '#444', fontStyle: 'italic', lineHeight: 20 },
  backBtn: { marginTop: 20, padding: 10, backgroundColor: '#999', alignItems: 'center', borderRadius: 5 }
});